//1.
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY >= 12000;

//2.
SELECT LAST_NAME, FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176;

//3. 급여를 5000 이하 받고 있는 사원의 성과 급여를 출력하라.
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY <= 5000;

//4.
SELECT LAST_NAME, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY >= 12000;

//5.
SELECT EMPLOYEE_ID, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 12000
ORDER BY SALARY DESC;

//6. 성이 Matos이거나 Taylor인 사원의 성과 시작날자, Job code를 출력하라.
//고용일이 빠른 사람이 먼저 출력되어야 한다.
SELECT LAST_NAME, HIRE_DATE, JOB_ID
FROM EMPLOYEES
WHERE LAST_NAME = 'Matos' or LAST_NAME = 'Taylor'
ORDER BY HIRE_DATE;

//7. 부서번호 20과 50사이인 사원의 성, 부서번호를 출력하라.
//성이 알파벳 역순으로 출력되어야 한다.
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 20 AND 50
ORDER BY LAST_NAME DESC;

//8. 50번 부서에서 일하는 사원들이 근무하는 Job id를 중복 제거하여 출려하라.
SELECT DISTINCT JOB_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50;

//9.
SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE LIKE '03%' OR HIRE_DATE LIKE '05%';

//10.
SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

//11.
SELECT EMPLOYEE_ID, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE NOT commission_pct IS NULL
ORDER BY SALARY, COMMISSION_PCT;

//12.
SELECT LAST_NAME, DEPARTMENT_ID, SALARY, JOB_ID
FROM EMPLOYEES
WHERE SALARY < 3000 AND DEPARTMENT_ID < 100;