/*
작성자: 정은애
작성일: 2018.06.12. (2)
pg 52~53
*/

--1. 100번 이하 부서에 소속된 사원의 사원번호, 성, 부서번호, 부서명을 출력하라.
SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS NATURAL JOIN EMPLOYEES
WHERE DEPARTMENT_ID < 100;

--2. 모든 부서의 주소를 출력한다. location ID, 
SELECT LOCATION_ID, STREET_ADDRESS, CITY, STATE_PROVINCE, COUNTRY_ID
FROM LOCATIONS NATURAL JOIN DEPARTMENTS;

--3. 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, e.JOB_ID, START_DATE, j.DEPARTMENT_ID
FROM JOB_HISTORY j JOIN EMPLOYEES e USING (EMPLOYEE_ID)
WHERE e.DEPARTMENT_ID >= 100;

--4. 
SELECT FIRST_NAME, LAST_NAME, JOB_TITLE
FROM EMPLOYEES NATURAL JOIN JOBS
WHERE SALARY < 5000;

--5. 
SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES e NATURAL JOIN DEPARTMENTS d 
NATURAL JOIN LOCATIONS l
WHERE l.CITY = 'Toronto';

/*SELECT e.LAST_NAME, e.JOB_ID, DEPARTMENT_ID, d.DEPARTMENT_NAME
FROM EMPLOYEES e NATURAL JOIN DEPARTMENTS d 
JOIN LOCATIONS l
ON (d.LOCATION_ID = l.LOCATION_ID)
WHERE l.CITY = 'Toronto';*/

--6.
SELECT e.EMPLOYEE_ID "EMP#", e.FIRST_NAME||'  '||e.LAST_NAME "EMP_NAME",  e.MANAGER_ID "MANAGER#", m.FIRST_NAME||'  '||m.LAST_NAME "MANAGER_NAME"
FROM EMPLOYEES e JOIN EMPLOYEES m
ON (e.MANAGER_ID = m.EMPLOYEE_ID);

--7.
SELECT e.EMPLOYEE_ID "EMP#", e.FIRST_NAME||'  '||e.LAST_NAME "EMP_NAME",  e.MANAGER_ID "MANAGER#", m.FIRST_NAME||'  '||m.LAST_NAME "MANAGER_NAME"
FROM EMPLOYEES e LEFT OUTER JOIN EMPLOYEES m
ON (e.MANAGER_ID = m.EMPLOYEE_ID);

--8.
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, JOB_TITLE
FROM EMPLOYEES NATURAL JOIN JOBS;

--9.
SELECT d.DEPARTMENT_ID, DEPARTMENT_NAME, e.FIRST_NAME
FROM DEPARTMENTS d JOIN EMPLOYEES e
ON (d.MANAGER_ID = e.EMPLOYEE_ID);

--10.
SELECT a.LAST_NAME "ANAME", DEPARTMENT_ID "DEPT", b.EMPLOYEE_ID "BEMP", b.LAST_NAME "BNAME"
FROM EMPLOYEES a JOIN EMPLOYEES b USING (DEPARTMENT_ID);

select e.last_name emp_name, e.department_id dept,
      c.employee_id col_emp_id, c.last_name col_name
from employees e join employees c 
on e.department_id = c.department_id;

--11.
SELECT j.LAST_NAME, j.HIRE_DATE, m.LAST_NAME, m.HIRE_DATE
FROM employees m join employees j
ON m.employee_id = j.MANAGER_ID
AND j.HIRE_DATE < m.HIRE_DATE;

select e.last_name, e.hire_date, m.last_name, m.hire_date
from employees e join employees m 
on e.manager_id = m.employee_id
where e.hire_date < m.hire_date;