CREATE TABLE CARD (
ID NUMBER(1) PRIMARY KEY, EXPRIATION DATE);

INSERT INTO CARD
VALUES(1, '18/06/03');

INSERT INTO CARD
VALUES(2, '17/06/29');

INSERT INTO CARD
VALUES(3, '18/03/31');

INSERT INTO CARD
VALUES(4, '18/12/31');

DELETE CARD
WHERE EXPRIATION < TO_DATE(SYSDATE,'YY/MM/DD');

CREATE TABLE book (
ID NUMBER(1) PRIMARY KEY, NAME varchar2(20), stock number(10), price number(10));

INSERT INTO book
VALUES(1, 'a', 0, 1000);

INSERT INTO book
VALUES(2, 'b', null, 2000);

INSERT INTO book
VALUES(3, 'c', 1, 3000);

INSERT INTO book
VALUES(4, 'd', 2, 5000);

INSERT INTO book
VALUES(5, 'e', 4, 12000);

INSERT INTO book
VALUES(6, 'f', 6, 7000);

SELECT NAME, STOCK, PRICE
FROM BOOK
WHERE (PRICE BETWEEN 5000 AND 10000) OR (STOCK IS NULL) OR STOCK = 0
ORDER BY PRICE;

select order_number, COUNT(BOOK_ID)
FROM BOOK_ORDER
GROUP BY ORDER_NUMBER
ORDER BY COUNT(BOOK_ID);